import type { PrimaryDomain } from "@/types";

export interface DomainMap {
  subfields: string[];
  jobTitles: string[];
  jobQueries: string[];
  eventQueries: string[];
  learningQueries: string[];
}

export const DOMAIN_EXPANSION: Record<PrimaryDomain, DomainMap> = {
  "Agentic AI": {
    subfields: [
      "Agentic AI",
      "AI Agents",
      "LLM Agents",
      "Multi-agent systems",
      "Tool-calling agents",
      "Workflow automation",
      "Autonomous AI systems",
      "RAG agents",
      "LangChain",
      "LangGraph",
      "CrewAI",
      "AutoGen",
      "OpenAI function calling",
      "Claude tool use",
      "AI automation",
      "AI assistants",
      "AI copilots",
      "Agent orchestration",
      "Memory systems",
      "Vector databases",
      "Prompt engineering",
    ],
    jobTitles: [
      "AI Agent Developer",
      "LLM Engineer",
      "AI Automation Specialist",
      "LangChain Developer",
      "Generative AI Engineer",
      "RAG Developer",
      "Prompt Engineer",
      "AI Engineer",
    ],
    jobQueries: [
      "AI Agent Developer intern Calgary remote",
      "LLM Engineer entry level Canada",
      "AI Automation Specialist junior",
      "LangChain Developer internship",
      "Generative AI Engineer entry level",
      "RAG Developer junior remote",
      "Prompt Engineer internship Canada",
    ],
    eventQueries: [
      "agentic AI event Calgary",
      "AI agents workshop Alberta",
      "LLM app development meetup Calgary",
      "generative AI hackathon Canada",
      "LangChain workshop online",
      "RAG systems webinar",
    ],
    learningQueries: [
      "beginner AI agents course",
      "LangChain agents course",
      "LangGraph tutorial",
      "RAG for beginners course",
      "OpenAI function calling tutorial",
      "multi-agent systems course",
      "AI automation with LLMs course",
    ],
  },
  "AI general": {
    subfields: [
      "Machine Learning",
      "Deep Learning",
      "Generative AI",
      "Agentic AI",
      "AI Automation",
      "Data Science",
      "Computer Vision",
      "NLP",
      "MLOps",
      "AI Engineering",
      "Prompt Engineering",
      "AI Product Management",
      "AI Ethics",
    ],
    jobTitles: [
      "AI Engineer",
      "Machine Learning Engineer",
      "Data Scientist",
      "AI Product Manager",
      "MLOps Engineer",
      "LLM Engineer",
    ],
    jobQueries: [
      "AI Engineer internship Canada",
      "Machine Learning intern Calgary",
      "Data Science intern Alberta",
      "AI Product intern Canada",
      "MLOps engineer entry level remote",
    ],
    eventQueries: [
      "AI event Calgary",
      "machine learning meetup Alberta",
      "data science hackathon Canada",
      "AI conference online",
      "ML workshop Calgary",
    ],
    learningQueries: [
      "machine learning course beginner",
      "deep learning fundamentals",
      "AI engineering course",
      "data science portfolio projects",
      "MLOps fundamentals",
    ],
  },
  "Machine Learning": {
    subfields: [
      "Supervised learning",
      "Unsupervised learning",
      "Reinforcement learning",
      "Deep learning",
      "scikit-learn",
      "PyTorch",
      "TensorFlow",
      "Feature engineering",
      "Model evaluation",
      "Hyperparameter tuning",
      "Kaggle competitions",
    ],
    jobTitles: [
      "Machine Learning Engineer",
      "ML Researcher",
      "Applied Scientist",
      "Data Scientist",
    ],
    jobQueries: [
      "Machine Learning intern Calgary",
      "ML Engineer entry level remote Canada",
      "Junior ML Engineer Alberta",
      "Applied ML researcher internship",
    ],
    eventQueries: [
      "machine learning meetup Alberta",
      "Kaggle competition kickoff",
      "PyTorch workshop online",
      "ML conference Canada",
    ],
    learningQueries: [
      "machine learning specialization",
      "fast.ai deep learning",
      "scikit-learn tutorial",
      "Kaggle Learn",
    ],
  },
  "Data Science": {
    subfields: [
      "SQL",
      "Pandas",
      "Tableau",
      "Power BI",
      "A/B testing",
      "Statistics",
      "Predictive modeling",
      "Data visualization",
      "Data engineering basics",
    ],
    jobTitles: [
      "Data Scientist",
      "Data Analyst",
      "Analytics Engineer",
      "Business Intelligence Analyst",
    ],
    jobQueries: [
      "Data Science intern Calgary",
      "Data Analyst intern Alberta",
      "Junior Data Scientist remote Canada",
    ],
    eventQueries: [
      "Calgary data science meetup",
      "data analytics workshop Alberta",
      "YYC DataCon",
    ],
    learningQueries: [
      "Python for data science",
      "SQL for data analysts",
      "Tableau beginner",
      "data science portfolio",
    ],
  },
  "Generative AI": {
    subfields: [
      "LLMs",
      "Diffusion models",
      "Stable Diffusion",
      "Image generation",
      "Text generation",
      "Audio generation",
      "Prompt engineering",
      "Fine-tuning",
      "RAG",
      "Evaluation",
    ],
    jobTitles: [
      "Generative AI Engineer",
      "LLM Engineer",
      "Prompt Engineer",
      "AI Engineer",
    ],
    jobQueries: [
      "Generative AI Engineer entry level",
      "LLM Engineer junior remote Canada",
      "Prompt Engineer internship",
    ],
    eventQueries: [
      "generative AI hackathon Canada",
      "LLM meetup Alberta",
      "diffusion models workshop",
      "PromptCon",
    ],
    learningQueries: [
      "generative AI fundamentals",
      "prompt engineering course",
      "fine-tune LLM tutorial",
      "diffusion models course",
    ],
  },
  NLP: {
    subfields: [
      "Tokenization",
      "Transformers",
      "BERT",
      "Hugging Face",
      "Named entity recognition",
      "Text classification",
      "Sentence embeddings",
      "Summarization",
      "RAG",
    ],
    jobTitles: ["NLP Engineer", "Applied Scientist NLP", "LLM Engineer", "Research Assistant"],
    jobQueries: [
      "NLP intern Canada",
      "NLP Engineer entry level",
      "NLP research assistant Calgary",
    ],
    eventQueries: ["NLP meetup", "Hugging Face workshop", "RAG webinar"],
    learningQueries: [
      "Hugging Face course",
      "NLP with transformers",
      "transformers from scratch",
    ],
  },
  "Computer Vision": {
    subfields: [
      "OpenCV",
      "PyTorch CV",
      "Image classification",
      "Object detection",
      "Segmentation",
      "Vision transformers",
      "Edge inference",
    ],
    jobTitles: ["Computer Vision Engineer", "CV Intern", "Applied Scientist CV", "Robotics Engineer"],
    jobQueries: [
      "Computer Vision intern Calgary",
      "CV Engineer entry level remote",
      "Vision Engineer Alberta",
    ],
    eventQueries: ["Computer Vision bootcamp", "OpenCV workshop", "CV meetup online"],
    learningQueries: [
      "computer vision course",
      "OpenCV tutorial",
      "PyTorch vision",
      "Vision Transformers course",
    ],
  },
  "AI Automation": {
    subfields: [
      "Workflow automation",
      "n8n",
      "Zapier",
      "Make.com",
      "Tool calling",
      "Webhook orchestration",
      "API integration",
      "RPA",
    ],
    jobTitles: ["AI Automation Specialist", "Automation Engineer", "Solutions Engineer"],
    jobQueries: [
      "AI Automation Specialist junior",
      "Automation Engineer entry level remote",
      "n8n developer Canada",
    ],
    eventQueries: ["AI automation meetup", "n8n workshop", "automation hackathon"],
    learningQueries: [
      "AI automation with LLMs course",
      "n8n tutorial",
      "Zapier OpenAI tutorial",
    ],
  },
  MLOps: {
    subfields: [
      "Docker",
      "Kubernetes",
      "CI/CD for ML",
      "Model monitoring",
      "Feature stores",
      "MLflow",
      "Kubeflow",
      "Weights & Biases",
    ],
    jobTitles: ["MLOps Engineer", "ML Platform Engineer", "DevOps for ML"],
    jobQueries: [
      "MLOps engineer entry level remote",
      "ML Platform intern Canada",
      "DevOps ML junior",
    ],
    eventQueries: ["MLOps meetup", "Kubeflow workshop", "ML platform conference"],
    learningQueries: ["MLOps fundamentals", "Docker for ML", "MLflow tutorial"],
  },
  "AI Product": {
    subfields: [
      "AI product strategy",
      "User research for AI",
      "AI UX patterns",
      "Eval & metrics",
      "Roadmapping",
      "Stakeholder communication",
    ],
    jobTitles: ["AI Product Manager", "AI Product Intern", "Product Analyst"],
    jobQueries: [
      "AI Product intern Canada",
      "AI Product Manager entry level",
      "Product Analyst AI",
    ],
    eventQueries: ["AI product meetup", "PM AI workshop", "AI product conference"],
    learningQueries: [
      "AI product management course",
      "Reforge AI product",
      "AI UX patterns course",
    ],
  },
};
