"use client";

import { useEffect, useState } from "react";
import { Check, Loader2, ListChecks, Clock, Trophy } from "lucide-react";
import { cn, minutesToHuman } from "@/lib/utils";
import { XPBar } from "@/components/XPBar";
import type { TaskCategory, TaskDoc, Weekday } from "@/types";

const WEEKDAYS: Weekday[] = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

const CATEGORY_LABEL: Record<TaskCategory, string> = {
  job_application: "Job",
  event: "Event",
  networking: "Network",
  resume: "Resume",
  linkedin: "LinkedIn",
  portfolio: "Portfolio",
  skill_building: "Skill",
  interview_practice: "Interview",
  career_admin: "Admin",
  follow_up: "Follow-up",
  learning: "Learn",
};

const CATEGORY_COLOR: Record<TaskCategory, string> = {
  job_application: "badge-accent",
  event: "badge",
  networking: "badge",
  resume: "badge-warn",
  linkedin: "badge",
  portfolio: "badge-accent",
  skill_building: "badge",
  interview_practice: "badge-danger",
  career_admin: "badge",
  follow_up: "badge-warn",
  learning: "badge-success",
};

export default function ChecklistPage() {
  const [data, setData] = useState<{
    weekStart: string;
    tasks: TaskDoc[];
    totalMinutes: number;
    totalXp: number;
    earnedXp: number;
  } | null>(null);
  const [updating, setUpdating] = useState<string | null>(null);

  async function load() {
    const r = await fetch("/api/checklist");
    setData(await r.json());
  }
  useEffect(() => {
    load();
  }, []);

  async function toggle(t: TaskDoc) {
    setUpdating(t._id!);
    const next = t.status === "done" ? "todo" : "done";
    await fetch(`/api/tasks/${t._id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: next }),
    });
    await load();
    setUpdating(null);
  }

  if (!data) {
    return <div className="text-muted"><Loader2 className="w-4 h-4 inline animate-spin mr-2" /> Loading checklist…</div>;
  }

  const tasksByDay: Record<Weekday, TaskDoc[]> = {
    Mon: [], Tue: [], Wed: [], Thu: [], Fri: [], Sat: [], Sun: [],
  };
  for (const t of data.tasks) tasksByDay[t.day].push(t);

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight">Weekly Checklist</h1>
          <p className="text-muted mt-1">
            Week of <span className="text-muted-strong">{data.weekStart}</span>. Generated by the Checklist Agent from approved opportunities.
          </p>
        </div>
        <div className="flex items-center gap-4 text-xs">
          <span className="inline-flex items-center gap-1 text-muted"><Clock className="w-3 h-3" /> {minutesToHuman(data.totalMinutes)}</span>
          <span className="inline-flex items-center gap-1 text-muted"><Trophy className="w-3 h-3" /> {data.earnedXp}/{data.totalXp} XP</span>
        </div>
      </div>

      <div className="card p-4">
        <XPBar earned={data.earnedXp} total={data.totalXp} />
      </div>

      {data.tasks.length === 0 ? (
        <div className="card p-10 text-center">
          <ListChecks className="w-5 h-5 text-accent mx-auto mb-2" />
          <p className="text-muted-strong">No tasks this week yet. Follow a job/event/course or paste an interview email to populate this checklist.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7 gap-3">
          {WEEKDAYS.map((d) => {
            const tasks = tasksByDay[d];
            const dayMins = tasks.reduce((n, t) => n + t.estimatedMinutes, 0);
            return (
              <div key={d} className="card p-3 space-y-2 min-h-[180px]">
                <div className="flex items-center justify-between">
                  <span className="text-white text-sm font-semibold">{d}</span>
                  <span className="text-[10px] text-muted">{tasks.length} · {minutesToHuman(dayMins)}</span>
                </div>
                <div className="space-y-2">
                  {tasks.length === 0 ? (
                    <p className="text-[11px] text-muted py-4 text-center">Free</p>
                  ) : (
                    tasks.map((t) => (
                      <button
                        key={t._id}
                        onClick={() => toggle(t)}
                        disabled={updating === t._id}
                        className={cn(
                          "w-full text-left p-2 rounded-lg border transition-colors",
                          t.status === "done"
                            ? "bg-success/5 border-success/30 text-muted line-through"
                            : "bg-bg-elevated border-border hover:border-border-strong",
                        )}
                      >
                        <div className="flex items-start gap-2">
                          <span className={cn(
                            "w-4 h-4 mt-0.5 rounded-full border grid place-items-center shrink-0",
                            t.status === "done" ? "bg-success border-success text-white" : "border-border",
                          )}>
                            {t.status === "done" && <Check className="w-3 h-3" />}
                          </span>
                          <span className="text-xs leading-snug flex-1 text-muted-strong">{t.title}</span>
                        </div>
                        <div className="mt-1.5 flex items-center justify-between text-[10px] text-muted">
                          <span className={CATEGORY_COLOR[t.category]}>{CATEGORY_LABEL[t.category]}</span>
                          <span>{t.estimatedMinutes}m · {t.xp}XP</span>
                        </div>
                      </button>
                    ))
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
